# Generated by Django 5.0.3 on 2024-12-05 20:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Admin1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("sports", "Sports"),
                    ("technology", "Technology"),
                    ("art", "Art"),
                    ("education", "Education"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
