# Generated by Django 5.0.3 on 2024-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Admin1", "0004_adminuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminUser",
        ),
    ]
